// Generated by build-icons.ts from svg. Do not edit it by hand:
// add or change an .svg file there, then run `bun run icons:build`.

export const ICON_VIEWBOX = '0 0 24 24'

export const icons = {
  'arrow-right': '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.75" d="M4 12h15m-5 5.657L19.657 12 14 6.343"/>',
  close: '<path d="M13.46 12 19 17.54V19h-1.46L12 13.46 6.46 19H5v-1.46L10.54 12 5 6.46V5h1.46L12 10.54 17.54 5H19v1.46z"/>',
  heart: '<path d="M18.5 3.8a7.4 7.4 0 0 1 3.5 6.6C21.86 16.5 13.5 21 12 21S2.14 16.5 2 10.4a7.4 7.4 0 0 1 3.5-6.6 5.6 5.6 0 0 1 6.5.54 5.6 5.6 0 0 1 6.5-.54"/>',
  menu: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 6h10M4 12h16M7 12h13M7 18h10"/>',
  search: '<path fill-rule="evenodd" d="M2.25 9.75a7.5 7.5 0 1 1 15 0 7.5 7.5 0 0 1-15 0M9.75 0a9.75 9.75 0 1 0 6.06 17.4l5.145 5.145.795.795 1.59-1.59-.795-.795L17.4 15.81A9.75 9.75 0 0 0 9.75 0" clip-rule="evenodd" shape-rendering="geometricprecision"/>',
  star: '<path d="M10.92 2.37a1.25 1.25 0 0 1 2.16 0l2.8 4.8 5.42 1.18a1.25 1.25 0 0 1 .67 2.05l-3.7 4.14.56 5.53a1.25 1.25 0 0 1-1.75 1.27L12 19.1l-5.08 2.24a1.25 1.25 0 0 1-1.75-1.27l.56-5.53-3.7-4.14a1.25 1.25 0 0 1 .67-2.06l5.43-1.17z"/>',
  'thumb-up': '<path d="M6 21h-.15A3 3 0 0 1 3 18v-6a3 3 0 0 1 2.85-3H6zM9.82 3.2c.3-.69 1.06-1.32 2.02-1.13C13.37 2.38 15 3.57 15 5.5V8h3.6c1.8 0 3.2 1.58 2.95 3.37l-.2 1.34-.92 5A4 4 0 0 1 16.5 21H8V9z"/>',
  trash: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.75" d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15m-9 4v7m4-7v7"/>',
}

export type IconName = keyof typeof icons

/** Scope SVG definitions and their references to one framework useId() value. */
export function iconMarkup(name: IconName, instanceId: string): string {
  const body = icons[name]
  const ids = new Map([...body.matchAll(/\sid="([^"]+)"/g)].map(([, id]) => [id, `icon-${Array.from(instanceId, c => c.codePointAt(0)!.toString(16)).join('-')}-${id}`]))
  if (!ids.size) return body
  const scoped = (id: string) => ids.get(id) ?? id
  let markup = body.replace(/ (id|href|xlink:href|aria-labelledby|aria-describedby|begin|end)="([^"]*)"/g, (attribute, key: string, value: string) => {
    if (key === 'id') return ` id="${scoped(value)}"`
    if (key === 'href' || key === 'xlink:href') return ` ${key}="${value.startsWith('#') ? '#' + scoped(value.slice(1)) : value}"`
    if (key.startsWith('aria-')) return ` ${key}="${value.split(/\s+/).map(scoped).join(' ')}"`
    return ` ${key}="${value.split(';').map(part => {
      const leading = part.match(/^\s*/)?.[0] ?? ''
      const timing = part.trimStart()
      // Longest first: IDs may contain dots, as may animation event names.
      const id = [...ids.keys()].sort((a, b) => b.length - a.length).find(id => timing.startsWith(id + '.'))
      return id ? leading + scoped(id) + timing.slice(id.length) : part
    }).join(';')}"`
  })
  markup = markup.replace(/url\(\s*(['"]?)#([^\s)'"]+)\1\s*\)/g, (_, quote: string, id: string) => `url(${quote}#${scoped(id)}${quote})`)
  // SVGO prefixes stylesheet selectors at build time; scope them at render time too.
  return markup.replace(/<style([^>]*)>([\s\S]*?)<\/style>/g, (_, attributes: string, css: string) =>
    `<style${attributes}>${css.replace(/#((?:\\.|[a-zA-Z0-9_-])+)/g, (match, selector: string) => {
      const id = selector.replace(/\\(.)/g, '$1')
      return ids.has(id) ? '#' + scoped(id).replace(/[^a-zA-Z0-9_-]/g, '\\$&') : match
    })}</style>`)
}
